version: '3.8'
services:
  bingo_bot:
    build: ./bot
    volumes:
      - ./bot:/app
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}

  bingo_server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"

  bingo_db:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  
volumes:
  mongo_data: {}
